version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: eshine-mysql
    ports:
      - 3306:3306
    networks:
      - eshine-pub
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: u![pSE9z96
      MYSQL_DATABASE: yolohde1_wp469
      MYSQL_USER: yolohde1_wp469
      MYSQL_PASSWORD: u![pSE9z96
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    networks:
      - eshine-pub
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: yolohde1_wp469
      WORDPRESS_DB_PASSWORD: u![pSE9z96
      WORDPRESS_DB_NAME: yolohde1_wp469
volumes:
  db_data: { }
networks:
  eshine-pub:


